export const ErrorCode = {
  // Config / manifest / asset validation (exit 2)
  CONFIG_INVALID: 'CONFIG_INVALID',
  MANIFEST_INVALID: 'MANIFEST_INVALID',
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_FORMAT_INVALID: 'ASSET_FORMAT_INVALID',
  ASSET_TOO_LARGE: 'ASSET_TOO_LARGE',
  ASSET_PATH_TRAVERSAL: 'ASSET_PATH_TRAVERSAL',

  // Authentication / access (exit 3)
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_MFA_IN_PROGRESS: 'AUTH_MFA_IN_PROGRESS',
  ACCESS_DENIED: 'ACCESS_DENIED',
  PENDO_UNAVAILABLE: 'PENDO_UNAVAILABLE',

  // Preflight / doctor (exit 4)
  APP_NOT_FOUND: 'APP_NOT_FOUND',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEMPLATE_AMBIGUOUS: 'TEMPLATE_AMBIGUOUS',
  TEMPLATE_FINGERPRINT_MISMATCH: 'TEMPLATE_FINGERPRINT_MISMATCH',
  TEMPLATE_NOT_DRAFT: 'TEMPLATE_NOT_DRAFT',
  TEMPLATE_APP_MISMATCH: 'TEMPLATE_APP_MISMATCH',
  PREFLIGHT_FAILED: 'PREFLIGHT_FAILED',

  // Duplicate / journal / resume (exit 5)
  DUPLICATE_GUIDE: 'DUPLICATE_GUIDE',
  JOURNAL_MISMATCH: 'JOURNAL_MISMATCH',
  JOURNAL_NOT_FOUND: 'JOURNAL_NOT_FOUND',
  JOURNAL_ALREADY_COMPLETED: 'JOURNAL_ALREADY_COMPLETED',
  RESUME_WITHOUT_JOURNAL: 'RESUME_WITHOUT_JOURNAL',
  RESUME_MANIFEST_HASH_MISMATCH: 'RESUME_MANIFEST_HASH_MISMATCH',
  RESUME_GUIDE_NOT_FOUND: 'RESUME_GUIDE_NOT_FOUND',
  RESUME_GUIDE_NOT_DRAFT: 'RESUME_GUIDE_NOT_DRAFT',
  RESUME_STATE_INCONSISTENT: 'RESUME_STATE_INCONSISTENT',

  // Lock conflicts (exit 6)
  RELEASE_LOCK_CONFLICT: 'RELEASE_LOCK_CONFLICT',
  PROFILE_LOCK_CONFLICT: 'PROFILE_LOCK_CONFLICT',

  // Pendo UI execution (exit 7)
  PENDO_NAVIGATION_TIMEOUT: 'PENDO_NAVIGATION_TIMEOUT',
  PENDO_SELECTOR_NOT_FOUND: 'PENDO_SELECTOR_NOT_FOUND',
  PENDO_SELECTOR_AMBIGUOUS: 'PENDO_SELECTOR_AMBIGUOUS',
  PENDO_CLONE_FAILED: 'PENDO_CLONE_FAILED',
  PENDO_RENAME_FAILED: 'PENDO_RENAME_FAILED',
  PENDO_STEP_COUNT_MISMATCH: 'PENDO_STEP_COUNT_MISMATCH',
  PENDO_DUPLICATE_STEP_FAILED: 'PENDO_DUPLICATE_STEP_FAILED',
  PENDO_TEXT_WRITE_FAILED: 'PENDO_TEXT_WRITE_FAILED',
  PENDO_TEXT_READBACK_MISMATCH: 'PENDO_TEXT_READBACK_MISMATCH',
  PENDO_IMAGE_UPLOAD_TIMEOUT: 'PENDO_IMAGE_UPLOAD_TIMEOUT',
  PENDO_IMAGE_UPLOAD_FAILED: 'PENDO_IMAGE_UPLOAD_FAILED',
  PENDO_IMAGE_REMOVE_FAILED: 'PENDO_IMAGE_REMOVE_FAILED',
  PENDO_SAVE_FAILED: 'PENDO_SAVE_FAILED',
  PENDO_UNEXPECTED_STATE: 'PENDO_UNEXPECTED_STATE',
  PENDO_GUIDE_PUBLISHED: 'PENDO_GUIDE_PUBLISHED',

  // Verification (exit 8)
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',

  // Internal (exit 9)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const EXIT_CODES: Record<string, number> = {
  [ErrorCode.CONFIG_INVALID]: 2,
  [ErrorCode.MANIFEST_INVALID]: 2,
  [ErrorCode.ASSET_NOT_FOUND]: 2,
  [ErrorCode.ASSET_FORMAT_INVALID]: 2,
  [ErrorCode.ASSET_TOO_LARGE]: 2,
  [ErrorCode.ASSET_PATH_TRAVERSAL]: 2,
  [ErrorCode.AUTH_REQUIRED]: 3,
  [ErrorCode.AUTH_MFA_IN_PROGRESS]: 3,
  [ErrorCode.ACCESS_DENIED]: 3,
  [ErrorCode.PENDO_UNAVAILABLE]: 3,
  [ErrorCode.APP_NOT_FOUND]: 4,
  [ErrorCode.TEMPLATE_NOT_FOUND]: 4,
  [ErrorCode.TEMPLATE_AMBIGUOUS]: 4,
  [ErrorCode.TEMPLATE_FINGERPRINT_MISMATCH]: 4,
  [ErrorCode.TEMPLATE_NOT_DRAFT]: 4,
  [ErrorCode.TEMPLATE_APP_MISMATCH]: 4,
  [ErrorCode.PREFLIGHT_FAILED]: 4,
  [ErrorCode.DUPLICATE_GUIDE]: 5,
  [ErrorCode.JOURNAL_MISMATCH]: 5,
  [ErrorCode.JOURNAL_NOT_FOUND]: 5,
  [ErrorCode.JOURNAL_ALREADY_COMPLETED]: 5,
  [ErrorCode.RESUME_WITHOUT_JOURNAL]: 5,
  [ErrorCode.RESUME_MANIFEST_HASH_MISMATCH]: 5,
  [ErrorCode.RESUME_GUIDE_NOT_FOUND]: 5,
  [ErrorCode.RESUME_GUIDE_NOT_DRAFT]: 5,
  [ErrorCode.RESUME_STATE_INCONSISTENT]: 5,
  [ErrorCode.RELEASE_LOCK_CONFLICT]: 6,
  [ErrorCode.PROFILE_LOCK_CONFLICT]: 6,
  [ErrorCode.PENDO_NAVIGATION_TIMEOUT]: 7,
  [ErrorCode.PENDO_SELECTOR_NOT_FOUND]: 7,
  [ErrorCode.PENDO_SELECTOR_AMBIGUOUS]: 7,
  [ErrorCode.PENDO_CLONE_FAILED]: 7,
  [ErrorCode.PENDO_RENAME_FAILED]: 7,
  [ErrorCode.PENDO_STEP_COUNT_MISMATCH]: 7,
  [ErrorCode.PENDO_DUPLICATE_STEP_FAILED]: 7,
  [ErrorCode.PENDO_TEXT_WRITE_FAILED]: 7,
  [ErrorCode.PENDO_TEXT_READBACK_MISMATCH]: 7,
  [ErrorCode.PENDO_IMAGE_UPLOAD_TIMEOUT]: 7,
  [ErrorCode.PENDO_IMAGE_UPLOAD_FAILED]: 7,
  [ErrorCode.PENDO_IMAGE_REMOVE_FAILED]: 7,
  [ErrorCode.PENDO_SAVE_FAILED]: 7,
  [ErrorCode.PENDO_UNEXPECTED_STATE]: 7,
  [ErrorCode.PENDO_GUIDE_PUBLISHED]: 7,
  [ErrorCode.VERIFICATION_FAILED]: 8,
  [ErrorCode.INTERNAL_ERROR]: 9,
};

export function exitCodeFor(code: string): number {
  return EXIT_CODES[code] ?? 9;
}
